package com.empdirectory.model.entity;

import oracle.jbo.server.EntityCache;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 09 00:03:59 CDT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DeptEOCollImpl extends EntityCache {
    /**
     * This is the default constructor (do not remove).
     */
    public DeptEOCollImpl() {
    }
}
