package com.empdirectory.model.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 10 23:40:03 CDT 2012
// ---------------------------------------------------------------------
public interface EmpDirectoryModule extends ApplicationModule {
    String getHelloWorld();
}
