package com.empdirectory.model.am.client;

import com.empdirectory.model.am.common.EmpDirectoryModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 10 23:40:03 CDT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmpDirectoryModuleClient extends ApplicationModuleImpl implements EmpDirectoryModule {
    /**
     * This is the default constructor (do not remove).
     */
    public EmpDirectoryModuleClient() {
    }

    public String getHelloWorld() {
        Object _ret = this.riInvokeExportedMethod(this,"getHelloWorld",null,null);
        return (String)_ret;
    }
}
