package com.empdirectory.model.entity;

import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 09 00:03:58 CDT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DeptEODefImpl extends EntityDefImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DeptEODefImpl() {
    }
}
